name = "hora-newsletter"
main = "worker.js"
compatibility_date = "2026-03-26"

[vars]
RESEND_AUDIENCE_ID = "3c81d864-8821-423f-af0e-61385ccbc511"

# RESEND_API_KEY should be set as a secret:
# npx wrangler secret put RESEND_API_KEY
