name = "hora-newsletter"
main = "worker.js"
compatibility_date = "2026-03-26"

[vars]
RESEND_AUDIENCE_ID = "3c81d864-8821-423f-af0e-61385ccbc511"
RESEND_WELCOME_TEMPLATE_ID = "0b03d32f-0ae8-4270-820c-6116ad0e15f2"
GA_MEASUREMENT_ID = "G-WQZ32S81FX"

# Secrets (set via `npx wrangler secret put`):
# RESEND_API_KEY, GA_API_SECRET
